# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"add_one_wire_modules": "00_device.ipynb",
         "DataPoint": "00_device.ipynb",
         "Device": "00_device.ipynb"}

modules = ["device.py"]

doc_url = "https://eandreas.github.io/ds18b20/"

git_url = "https://github.com/eandreas/ds18b20/tree/master/"

def custom_doc_links(name): return None
